language_complex_analysis = {
    "RU": {
        "title": "📐  Комплексный анализ данных",
        "main_info": "📌 Основная информация",
        "total_records": "Всего записей",
        "num_features": "Количество признаков",
        "missing_values": "Пропущенные значения",
        "data_types": "**Типы данных:**",
        "column": "Колонка",
        "type": "Тип",
        "select_columns": "Выберите колонки для анализа",
        "no_columns_selected": "Пожалуйста, выберите колонки для анализа",
        "statistics": "📈 Статистики",
        "numeric_stats": "Числовые характеристики",
        "categorical_stats": "Категориальные характеристики",
        "column_name": "Колонка",
        "unique_values": "Уникальные",
        "most_frequent": "Самое частое",
        "frequency": "Частота",
        "visualizations": "📊 Визуализации",
        "distributions": "Распределения",
        "correlations": "Корреляции",
        "missing_values_heatmap": "Пропущенные значения",
        "categorical_analysis": "Категориальный анализ",
        "select_numeric_column": "Выберите числовую колонку",
        "distribution": "Распределение",
        "boxplot": "Boxplot",
        "correlation_matrix": "Матрица корреляций",
        "need_more_numeric_cols": "Нужно минимум 2 числовые колонки",
        "missing_values_matrix": "Матрица пропущенных значений",
        "missing_values_heatmap_title": "Пропущенные значения (желтый = пропуск)",
        "select_categorical_column": "Выберите категориальную колонку",
        "top_n_values": "Количество топ-значений",
        "no_numeric_cols": "Нет числовых колонок для анализа",
        "no_categorical_cols": "Нет категориальных колонок",
        "detailed_analysis": "🔍 Детальный анализ",
        "data_preview": "Просмотр данных",
        "num_rows": "Количество строк для отображения",
        "show_column_info": "Показать полную информацию о колонках",
        "first_values": "Первые значения:",
        "unique_values_count": "Уникальных значений:",
        "analysis_complete": "Анализ завершен! 🎉",
        'in': "в",

    },
    "EN": {
        "title": "📐 Complex Data Analysis",
        "main_info": "📌 Main Information",
        "total_records": "Total Records",
        "num_features": "Number of Features",
        "missing_values": "Missing Values",
        "data_types": "**Data Types:**",
        "column": "Column",
        "type": "Type",
        "select_columns": "Select columns for analysis",
        "no_columns_selected": "Please select columns for analysis",
        "statistics": "📈 Statistics",
        "numeric_stats": "Numeric Characteristics",
        "categorical_stats": "Categorical Characteristics",
        "column_name": "Column",
        "unique_values": "Unique Values",
        "most_frequent": "Most Frequent",
        "frequency": "Frequency",
        "visualizations": "📊 Visualizations",
        "distributions": "Distributions",
        "correlations": "Correlations",
        "missing_values_heatmap": "Missing Values",
        "categorical_analysis": "Categorical Analysis",
        "select_numeric_column": "Select a numeric column",
        "distribution": "Distribution",
        "boxplot": "Boxplot",
        "correlation_matrix": "Correlation Matrix",
        "need_more_numeric_cols": "At least 2 numeric columns are needed",
        "missing_values_matrix": "Missing Values Matrix",
        "missing_values_heatmap_title": "Missing Values (yellow = missing)",
        "select_categorical_column": "Select a categorical column",
        "top_n_values": "Number of top values",
        "no_numeric_cols": "No numeric columns for analysis",
        "no_categorical_cols": "No categorical columns",
        "detailed_analysis": "🔍 Detailed Analysis",
        "data_preview": "Data Preview",
        "num_rows": "Number of rows to display",
        "show_column_info": "Show full column information",
        "first_values": "First values:",
        "unique_values_count": "Unique values:",
        "analysis_complete": "Analysis complete! 🎉",
        'in': "in",
    }
}

language_dynamic_analysis = {
    "EN": {
        "title": "Interactive Cascading Filters with Streamlit",
        "filter_columns": "Select columns for filtering (order determines cascading)",
        "filter_label": "Filter by {} ({} options available)",
        "results_header": "Filter Results",
        "found_records": "Records found: {}",
        "analysis_header": "Data Analysis",
        "grouping_header": "Grouping and Aggregation",
        "group_columns": "Group by columns",
        "agg_columns": "Aggregation columns",
        "pivot_header": "Pivot Table",
        "pivot_rows": "Rows",
        "pivot_columns": "Columns",
        "pivot_values": "Values",
        "agg_function": "Aggregation function",
        "group_result": "Grouping result:",
        "pivot_result": "Pivot table:",
        "error_grouping": "Error in grouping: {}",
        "error_pivot": "Error creating pivot table: {}"
    },
    "RU": {
        "title": "Интерактивные каскадные фильтры с Streamlit",
        "filter_columns": "Выберите колонки для фильтрации (порядок определяет каскадность)",
        "filter_label": "Фильтр по {} (доступно {} вариантов)",
        "results_header": "Результаты фильтрации",
        "found_records": "Найдено записей: {}",
        "analysis_header": "Анализ данных",
        "grouping_header": "Группировка и агрегация",
        "group_columns": "Колонки для группировки",
        "agg_columns": "Колонки для агрегации",
        "pivot_header": "Сводная таблица",
        "pivot_rows": "Строки",
        "pivot_columns": "Столбцы",
        "pivot_values": "Значения",
        "agg_function": "Агрегационная функция",
        "group_result": "Результат группировки:",
        "pivot_result": "Сводная таблица:",
        "error_grouping": "Ошибка при группировке: {}",
        "error_pivot": "Ошибка создания сводной таблицы: {}"
    }
}